baseURL = "http://emiguelt.mysu.co/"
languageCode = "en-us"
title = "Edwin Miguel, My Site"
theme = "er"
enableGitInfo = true
PygmentsCodeFences = true
PygmentsStyle = "monokai"
disqusShortname = "emiguelwebpage"
googleAnalytics  = "UA-46201600-1"
